#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

MUNIN_PLUGINS="
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Setup elasticsearch"
touch /opt/local/etc/elasticsearch/elasticsearch.keystore
chown root:elasticsearch /opt/local/etc/elasticsearch/elasticsearch.keystore

mv /opt/local/java/openjdk8/jre/lib/security/java.policy /opt/local/java/openjdk8/jre/lib/security/java.policy.bak
mv /var/zoneinit/tmp/java.policy /opt/local/java/openjdk8/jre/lib/security/java.policy

mv /opt/local/etc/elasticsearch/elasticsearch.yml /opt/local/etc/elasticsearch/elasticsearch.yml.bak
mv /var/zoneinit/tmp/elasticsearch.yml /opt/local/etc/elasticsearch/elasticsearch.yml

# /opt/local/lib/svc/manifest/elasticsearch.xml

echo "* Setup nginx"
mkdir -p /opt/local/etc/nginx/ssl

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
